name: Clang Format Check

on: [push, pull_request]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up clang-format
        run: sudo apt-get install -y clang-format

      - name: Check code formatting
        run: |
          find . -name "*.h" -o -name "*.hpp" -o -name "*.c" -o -name "*.cpp" -print0 | xargs -0 clang-format --dry-run --Werror -style=file
